# 单个角色显示布局
<SkinItemLayout>:
    size_hint: None, None
    size: dp(140), dp(210)
    orientation: 'vertical'
    padding: dp(2),dp(2),dp(2), dp(2)
    MainBoxLayout:
        id: box_layout
        Image:
            source: root.image_source
            pos: box_layout.x, box_layout.y
            size: box_layout.width, box_layout.height
    ClickLabel:
        id: role_label
        size_hint: 1,None
        height: dp(25)