# 次要色滚动布局
<PartScrollView@ScrollView>:
    do_scroll_x: False
    do_scroll_y: True
    canvas.before:
        Color:
            rgba: app.part_color
        Rectangle:
            pos: self.pos
            size: self.size

<MainScrollView@ScrollView>
    do_scroll_x: False
    do_scroll_y: True
    canvas.before:
        Color:
            rgba: app.main_color
        Rectangle:
            pos: self.pos
            size: self.size