# 侧边栏模窗
<SidebarModalView>:
    id: sidebar_view
    size_hint: 0.15, 1
    pos_hint: {'x':0}
    PartScrollView:
        PartBoxLayout:
            size_hint: 1,None
            orientation: 'vertical'
            spacing: dp(8)
            padding: dp(8)
            height: self.minimum_height

            HoverLabel:
                id: page_skinManage
                text: '皮肤管理'
                size_hint_y: None
                height: dp(35)
